server:
  port: 30991
  servlet:
    context-path: /jay-admin

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testplus?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456789
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    port: 6379
    # Redis数据库索引（默认为0）
    database: 1
    timeout: 5000
#    线程安全
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  jta:
    atomikos:
      datasource:
        xa-data-source-class-name:
#    线程不安全
#    jedis:
#      pool:
#        max-active: 50
#        max-wait: 3000
#        max-idle: 20
#        min-idle: 2
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: saToken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒  -1永不过期  有操作则会续签
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格   uuid;simple-uuid;random-32;random-64;random-128;tik
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  #配置 Sa-Token 单独使用Redis连接
  alone-redis:
    #数据库索引
    database: 2
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 10s
  sso:
    auth-url: http://sa-sso-server.com:9000/sso/auth


# xxl-job 配置文件
#xxl:
  #job:
    #admin:
      #addresses: http://127.0.0.1:8088/xxl-job-admin
    #accessToken:
    #executor:
      #appname: xxl-job-executor-sample
      #ip:
      #port: 30992
      #logpath:
      #logretentiondays:

  #去掉token的前缀读取 如：
  #{
  #    "satoken": "Bearer xxxx-xxxx-xxxx-xxxx"
  #}
  #  Token前缀 与 Token值 之间必须有一个空格。
  #  一旦配置了 Token前缀，则前端提交 Token 时，必须带有前缀，否则会导致框架无法读取 Token。
  #  由于Cookie中无法存储空格字符，也就意味配置 Token 前缀后，Cookie 鉴权方式将会失效，此时只能将 Token 提交到header里进行传输
  token-prefix: Bearer

#redis

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/testplus?useUnicode=true&characterEncoding=UTF-8
#spring.datasource.username=root
#spring.datasource.password=123456789
#
#mybatis-plus.mapper-locations=classpath:/mapper/*.xml
#
#
##redis??
##Redis?????
#spring.redis.host=127.0.0.1
##Redis???????
#spring.redis.port=6379
##Redis?????????0?
#spring.redis.database=0
##????????????????????
#spring.redis.jedis.pool.max-active=50
##???????????????????????
#spring.redis.jedis.pool.max-wait=3000
##???????????
#spring.redis.jedis.pool.max-idle=20
##???????????
#spring.redis.jedis.pool.min-idle=2
##??????????
#spring.redis.timeout=5000

test.jay.private_key: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAO+wmt01pwm9lHMdq7A8gkEigk0XKMfjv+4IjAFhWCSiTeP7dtlnceFJbkWxvbc7Qo3fCOpwmfcskwUc3VSgyiJkNJDs9ivPbvlt8IU2bZ+PBDxYxSCJFrgouVOpAr8ar/b6gNuYTi1vt3FkGtSjACFb002/68RKUTye8/tdcVilAgMBAAECgYA1COmrSqTUJeuD8Su9ChZ0HROhxR8T45PjMmbwIz7ilDsR1+E7R4VOKPZKW4Kz2VvnklMhtJqMs4MwXWunvxAaUFzQTTg2Fu/WU8Y9ha14OaWZABfChMZlpkmpJW9arKmI22ZuxCEsFGxghTiJQ3tK8npj5IZq5vk+6mFHQ6aJAQJBAPghz91Dpuj+0bOUfOUmzi22obWCBncAD/0CqCLnJlpfOoa9bOcXSusGuSPuKy5KiGyblHMgKI6bq7gcM2DWrGUCQQD3SkOcmia2s/6i7DUEzMKaB0bkkX4Ela/xrfV+A3GzTPv9bIBamu0VIHznuiZbeNeyw7sVo4/GTItq/zn2QJdBAkEA8xHsVoyXTVeShaDIWJKTFyT5dJ1TR++/udKIcuiNIap34tZdgGPI+EM1yoTduBM7YWlnGwA9urW0mj7F9e9WIQJAFjxqSfmeg40512KP/ed/lCQVXtYqU7U2BfBTg8pBfhLtEcOg4wTNTroGITwe2NjL5HovJ2n2sqkNXEio6Ji0QQJAFLW1Kt80qypMqot+mHhS+0KfdOpaKeMWMSR4Ij5VfE63WzETEeWAMQESxzhavN1WOTb3/p6icgcVbgPQBaWhGg==

test.jay.public_key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDvsJrdNacJvZRzHauwPIJBIoJNFyjH47/uCIwBYVgkok3j+3bZZ3HhSW5Fsb23O0KN3wjqcJn3LJMFHN1UoMoiZDSQ7PYrz275bfCFNm2fjwQ8WMUgiRa4KLlTqQK/Gq/2+oDbmE4tb7dxZBrUowAhW9NNv+vESlE8nvP7XXFYpQIDAQAB




